// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWjWDdeMr5gfeei36V0HfcWpogTidE5mc',
    appId: '1:876848753270:web:f2f16d7dc43544f3b8cd57',
    messagingSenderId: '876848753270',
    projectId: 'test-avalon2',
    authDomain: 'test-avalon2.firebaseapp.com',
    storageBucket: 'test-avalon2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcupHtsRiu_5lq9wYHIYhZ9le3MKqwLhw',
    appId: '1:876848753270:android:af00292dab37b684b8cd57',
    messagingSenderId: '876848753270',
    projectId: 'test-avalon2',
    storageBucket: 'test-avalon2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0T3aCH3nmlhp69HGJ2PdWbDLWdQfRsMg',
    appId: '1:876848753270:ios:54e44bda6c88801cb8cd57',
    messagingSenderId: '876848753270',
    projectId: 'test-avalon2',
    storageBucket: 'test-avalon2.appspot.com',
    iosBundleId: 'com.example.testAvalon2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0T3aCH3nmlhp69HGJ2PdWbDLWdQfRsMg',
    appId: '1:876848753270:ios:16c8cad053ab825ab8cd57',
    messagingSenderId: '876848753270',
    projectId: 'test-avalon2',
    storageBucket: 'test-avalon2.appspot.com',
    iosBundleId: 'com.example.testAvalon2.RunnerTests',
  );
}
